import { PrismaClient } from '@prisma/client';

export async function seedQuestions(prisma: PrismaClient) {
  // Clear existing questions before seeding to ensure fresh start
  await prisma.feladatok.deleteMany();
  
  const questions = [
    // 1. Alapfogalmak
    {
      title: 'Alapfogalmak',
      question: 'Mi a környezetvédelem elsődleges célja?',
      answers: JSON.stringify(['Az ipari termelés maximalizálása fenntartható módon', 'Kizárólag a vadon élő állatfajok populációjának védelme', 'Az emberi kényelem és technológiai fölény kiszolgálása', 'Az élővilág és az emberi életfeltételek hosszú távú megőrzése']),
      correct: 'Az élővilág és az emberi életfeltételek hosszú távú megőrzése',
      funfact: 'A környezetvédelem nem csak a természetéért van; az emberi egészség és a gazdasági stabilitás is közvetlenül függ a tiszta környezettől.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent az "ökológiai lábnyom" kifejezés?',
      answers: JSON.stringify(['Egy adott területen hagyott fizikai nyomok összessége', 'Egy nemzet gazdasági fejlődésének környezeti mutatója', 'A globális cipőgyártás ökológiai hatásainak mértéke', 'Az életmódunk fenntartásához szükséges erőforrások mennyisége']),
      correct: 'Az életmódunk fenntartásához szükséges erőforrások mennyisége',
      funfact: 'Ha mindenki úgy élne, mint egy átlagos európai, közel 3 Földre lenne szükségünk az erőforrások fenntartásához.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Melyik gáz a felelős leginkább az üvegházhatás fokozódásáért az emberi tevékenység révén?',
      answers: JSON.stringify(['Oxigén', 'Hidrogén', 'Argon', 'Szén-dioxid']),
      correct: 'Szén-dioxid',
      funfact: 'Bár a vízgőz a legerősebb üvegházhatású gáz, a légköri szén-dioxid szintje az ipari forradalom óta több mint 45%-kal nőtt.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a fenntartható fejlődés lényege?',
      answers: JSON.stringify(['Csak a jelen generáció igényeinek kielégítése', 'A technológiai fejlődés leállítása', 'A természet teljes érintetlensége', 'A jelen igényeinek kielégítése úgy, hogy az ne veszélyeztesse a jövő generációk szükségleteit']),
      correct: 'A jelen igényeinek kielégítése úgy, hogy az ne veszélyeztesse a jövő generációk szükségleteit',
      funfact: 'A fogalmat 1987-ben, a Brundtland-jelentésben (Közös jövőnk) határozták meg először hivatalosan.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit nevezünk biodiverzitásnak?',
      answers: JSON.stringify(['A különböző technológiák sokszínűségét', 'Az elektromos autók elterjedését', 'A szelektív hulladékgyűjtést', 'Az élővilág, a fajok és az ökoszisztémák sokféleségét']),
      correct: 'Az élővilág, a fajok és az ökoszisztémák sokféleségét',
      funfact: 'A Földön eddig körülbelül 1,7 millió fajt írtak le, de a becslések szerint akár 8-10 millió faj is létezhet.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a globális felmelegedés egyik fő következménye?',
      answers: JSON.stringify(['Az óceánok szintjének csökkenése', 'A sarki jégsapkák növekedése', 'A vulkáni aktivitás megszűnése', 'A szélsőséges időjárási események gyakoriságának növekedése']),
      correct: 'A szélsőséges időjárási események gyakoriságának növekedése',
      funfact: 'Az utóbbi évtizedekben a hőhullámok, aszályok és heves esőzések száma világszerte jelentősen megugrott.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a célja a 2015-ös Párizsi Megállapodásnak?',
      answers: JSON.stringify(['Az űrkutatás támogatása', 'A világgazdaság központosítása', 'A műanyaggyártás betiltása 2020-ig', 'A globális átlaghőmérséklet emelkedésének 2 Celsius-fok alatt tartása']),
      correct: 'A globális átlaghőmérséklet emelkedésének 2 Celsius-fok alatt tartása',
      funfact: 'Ez volt az első olyan jogilag kötelező erejű nemzetközi szerződés, amely szinte minden országot összefogott a klímaváltozás ellen.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Milyen típusú erőforrás a napenergia?',
      answers: JSON.stringify(['Fosszilis', 'Véges', 'Kimerülő', 'Megújuló']),
      correct: 'Megújuló',
      funfact: 'A Nap egyetlen óra alatt annyi energiát sugároz a Földre, amennyit az egész emberiség egy év alatt felhasznál.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit mér az ökoszisztéma-szolgáltatás?',
      answers: JSON.stringify(['A környezetvédelmi hatóságok munkáját', 'A napelemek hatékonyságát', 'Az állatkertek látogatottságát', 'A természet által az emberiségnek nyújtott hasznokat (pl. beporzás, tiszta levegő)']),
      correct: 'A természet által az emberiségnek nyújtott hasznokat (pl. beporzás, tiszta levegő)',
      funfact: 'A rovarok általi beporzás értékét világszinten évi több százmilliárd euróra becsülik.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent a dekarbonizáció?',
      answers: JSON.stringify(['A szénbányászat növelését', 'A gyémántkészítés folyamatát', 'A növények szénfelvételének gátlását', 'Az üvegházhatású gázok kibocsátásának csökkentését vagy megszüntetését']),
      correct: 'Az üvegházhatású gázok kibocsátásának csökkentését vagy megszüntetését',
      funfact: 'A dekarbonizáció kulcsa a fosszilis tüzelőanyagokról a tiszta energiára való teljes átállás.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi az invazív faj fogalma?',
      answers: JSON.stringify(['Egy veszélyeztetett őshonos állat', 'Egy kihalófélben lévő növény', 'Mesterségesen létrehozott hibrid faj', 'Olyan idegenhonos faj, amely megtelepedése után károsítja az új környezetét']),
      correct: 'Olyan idegenhonos faj, amely megtelepedése után károsítja az új környezetét',
      funfact: 'Az invazív fajok (pl. parlagfű) világszerte az egyik legfőbb okozói az őshonos élővilág pusztulásának.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Melyik szervezet az ENSZ legfőbb környezetvédelmi szerve?',
      answers: JSON.stringify(['NASA', 'WHO', 'UNICEF', 'UNEP']),
      correct: 'UNEP',
      funfact: 'Az UNEP székhelye a kenyai Nairobiban található, és 1972 óta koordinálja a globális környezetvédelmi erőfeszítéseket.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi az ózonréteg feladata?',
      answers: JSON.stringify(['A szén-dioxid elnyelése', 'A felhőképződés segítése', 'A levegő lehűtése', 'A Nap káros ultraibolya (UV) sugárzásának elnyelése']),
      correct: 'A Nap káros ultraibolya (UV) sugárzásának elnyelése',
      funfact: 'Az ózonlyuk gyógyulóban van a CFC-gázok betiltásának köszönhetően, ami a modern környezetvédelem egyik legnagyobb sikere.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit nevezünk túlfogyasztási napnak?',
      answers: JSON.stringify(['A karácsonyi bevásárlási időszakot', 'Amikor a boltokban kiárusítás van', 'Az év utolsó napját', 'Azt a dátumot, amikor az emberiség elhasználja a Föld adott évre vonatkozó erőforrásait']),
      correct: 'Azt a dátumot, amikor az emberiség elhasználja a Föld adott évre vonatkozó erőforrásait',
      funfact: '1970-ben még december végén volt ez a nap, ma már gyakran júliusra vagy augusztusra esik.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a megújuló energiaforrások egyik legnagyobb előnye?',
      answers: JSON.stringify(['Hogy drágábbak a szénnél', 'Hogy mindenhol egyformán elérhetőek', 'Hogy nem igényelnek karbantartást', 'Hogy üzemeltetésük során alacsony vagy nulla a károsanyag-kibocsátásuk']),
      correct: 'Hogy üzemeltetésük során alacsony vagy nulla a károsanyag-kibocsátásuk',
      funfact: 'A szél- és napenergia ára az utóbbi évtizedben drasztikusan csökkent, így ma már sok helyen olcsóbbak a szénnél.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent a környezetterhelési díj?',
      answers: JSON.stringify(['A szemétszállítási díjat', 'A környezetbarát termékek adóját', 'Egy önkéntes adományt a Greenpeace-nek', 'A környezethasználó által fizetett díjat a környezet igénybevételéért']),
      correct: 'A környezethasználó által fizetett díjat a környezet igénybevételéért',
      funfact: 'A "szennyező fizet" elv alapján a vállalatokat arra ösztönzi, hogy korszerűsítsék technológiáikat.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a "zöldmosás" (greenwashing)?',
      answers: JSON.stringify(['A ruhák környezetbarát mosása', 'A napelemek tisztítása vízzel', 'A fák lemosása az erdőtüzek után', 'Egy vállalat megtévesztő stratégiája, amellyel környezetbarátabbnak tünteti fel magát a valóságnál']),
      correct: 'Egy vállalat megtévesztő stratégiája, amellyel környezetbarátabbnak tünteti fel magát a valóságnál',
      funfact: 'Sok cég használ "természetes" vagy "öko" jelzőket olyan termékekre, amelyek valójában nem fenntarthatók.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Melyik szektor felelős globálisan a legtöbb üvegházhatású gáz kibocsátásáért?',
      answers: JSON.stringify(['Szemétszállítás', 'Divatipar', 'Turizmus', 'Energiaellátás (villamosenergia- és hőtermelés)']),
      correct: 'Energiaellátás (villamosenergia- és hőtermelés)',
      funfact: 'Az energiaszektor felelős a globális kibocsátások körülbelül 35%-áért.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a biomassza?',
      answers: JSON.stringify(['Műanyag hulladék halmaza', 'Ásványi kőzetek összessége', 'Fémhulladék újrahasznosításra', 'Biológiai úton lebomló szerves anyagok összessége']),
      correct: 'Biológiai úton lebomló szerves anyagok összessége',
      funfact: 'A biomassza elégetésekor CO2 szabadul fel, de mivel a növények növekedés közben ezt elnyelik, karbonsemlegesnek tekinthető.',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent az ökocímke a termékeken?',
      answers: JSON.stringify(['Hogy a termék nagyon drága', 'Hogy a terméket külföldről hozták', 'Hogy a termék zöld színű', 'Hogy a termék életciklusa során bizonyítottan kisebb terhelést jelent a környezetre']),
      correct: 'Hogy a termék életciklusa során bizonyítottan kisebb terhelést jelent a környezetre',
      funfact: 'Az Európai Unióban a "Virág" logó (EU Ecolabel) az egyik legismertebb tanúsító védjegy.',
      history: '',
    },

    // 2. Újrahasznosítás
    {
      title: 'Újrahasznosítás',
      question: 'Melyik anyag hasznosítható újra szinte végtelen alkalommal minőségromlás nélkül?',
      answers: JSON.stringify(['Papír', 'Műanyag', 'Textil', 'Üveg']),
      correct: 'Üveg',
      funfact: 'Egyetlen üvegpalack újrahasznosításával annyi energiát takaríthatunk meg, amennyivel egy laptop órákig működhetne.',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Milyen színű gyűjtőedénybe kell dobni a tiszta papírhulladékot Magyarországon?',
      answers: JSON.stringify(['Sárga', 'Szürke', 'Fehér', 'Kék']),
      correct: 'Kék',
      funfact: 'A papír körülbelül 5-7 alkalommal hasznosítható újra, mielőtt a rostok túl gyengék lennének.',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a szelektív hulladékgyűjtés legfontosabb szabálya a műanyag flakonoknál?',
      answers: JSON.stringify(['Maradék folyadékkal együtt kell gyűjteni', 'Tilos a flakonokat bármilyen módon összenyomni', 'Minden esetben el kell távolítani a papírcímkét', 'Kiöblítés után laposra taposva kell kidobni']),
      correct: 'Kiöblítés után laposra taposva kell kidobni',
      funfact: 'Az összenyomott flakonokból sokkal több fér el a szállítóautókban, így kevesebb CO2-kibocsátással jár a szállításuk.',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi történik a papírral minden egyes újrahasznosítási ciklus során?',
      answers: JSON.stringify(['Fehéredik', 'Egyre vastagabb lesz', 'Megszínesedik', 'A cellulózrostok rövidülnek és gyengülnek']),
      correct: 'A cellulózrostok rövidülnek és gyengülnek',
      funfact: 'Ezért kell minden ciklusban valamennyi friss farostot is hozzáadni az új papírgyártáshoz.',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi az újrahasznosítás (recycle) és az újrafelhasználás (reuse) közötti különbség?',
      answers: JSON.stringify(['Nincs érdemi különbség a két fogalom között', 'Az újrafelhasználás ipari, az újrahasznosítás otthoni', 'Az újrahasznosítás minden esetben költséghatékonyabb', 'Az újrafelhasználásnál a tárgy formája nem változik']),
      correct: 'Az újrafelhasználásnál a tárgy formája nem változik',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Melyik hulladékfajtát nevezzük "e-hulladéknak"?',
      answers: JSON.stringify(['Biológiai úton lebomló ételmaradék', 'Használt higiéniai papírtermékek', 'Építkezésből származó törmelék', 'Elromlott elektronikai eszközök']),
      correct: 'Elromlott elektronikai eszközök',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Miért veszélyes az elem a rendes szemétben?',
      answers: JSON.stringify(['Kellemetlen szagokat okoz a kukában', 'Fizikai sérülést okozhat a gépkezelőknek', 'Zavarja a papírhulladék válogatását', 'Mérgező nehézfémeket juttat a talajba']),
      correct: 'Mérgező nehézfémeket juttat a talajba',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a komposztálás fő célja?',
      answers: JSON.stringify(['Műanyag csomagolások lebontása', 'Fém alkatrészek kémiai tisztítása', 'Szennyezett papírok megsemmisítése', 'Szerves anyagok tápdússá alakítása']),
      correct: 'Szerves anyagok tápdússá alakítása',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Körülbelül mennyi idő alatt bomlik le egy műanyag palack a természetben?',
      answers: JSON.stringify(['1-2 év', '10-20 év', '100-150 év', '450-500 év (vagy soha teljesen)']),
      correct: '450-500 év (vagy soha teljesen)',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a sárga szelektív kuka elsődleges tartalma Magyarországon?',
      answers: JSON.stringify(['Csak üveg', 'Csak újságpapír', 'Csak ételmaradék', 'Műanyag és gyakran fém csomagolási hulladék']),
      correct: 'Műanyag és gyakran fém csomagolási hulladék',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a cirkuláris (körforgásos) gazdaság alapelve?',
      answers: JSON.stringify(['A termékek égetéses megsemmisítése', 'Minden termék kör alakúra tervezése', 'A folyamatos gazdasági növekedés', 'A hulladékmentes anyagkörforgás']),
      correct: 'A hulladékmentes anyagkörforgás',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Milyen hulladékot nem szabad a komposztba tenni?',
      answers: JSON.stringify(['Összetört tojáshéj', 'Használt kávézacc', 'Száraz őszi falevél', 'Hús- és tejtermék maradék']),
      correct: 'Hús- és tejtermék maradék',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mit jelent a "downcycling" kifejezés?',
      answers: JSON.stringify(['A használt kerékpárok felújítása', 'Az anyagminőség teljes megőrzése', 'Az újrahasznosítási díjak csökkentése', 'Alacsonyabb minőségű feldolgozás']),
      correct: 'Alacsonyabb minőségű feldolgozás',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi az alumíniumdobozok újrahasznosításának legnagyobb előnye?',
      answers: JSON.stringify(['Esztétikusabb megjelenésű dobozok', 'A fémfalak súlyának csökkenése', 'A tisztítási folyamat vízigénye', 'Jelentős (95%) energiamegtakarítás']),
      correct: 'Jelentős (95%) energiamegtakarítás',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Hova kell vinni a használt gumiabroncsokat?',
      answers: JSON.stringify(['A kommunális kukába', 'Az erdő szélére', 'A papírgyűjtőbe', 'Hulladékudvarba vagy gumiabroncs-szervizbe']),
      correct: 'Hulladékudvarba vagy gumiabroncs-szervizbe',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Miért nem dobható a tükör vagy a hőálló üveg a szelektív üveggyűjtőbe?',
      answers: JSON.stringify(['A súlyuk miatt nem szállíthatóak', 'Eltérő az üveganyagok színezése', 'Babonák tiltják a tükördobást', 'Eltérő az olvadáspontjuk és összetételük']),
      correct: 'Eltérő az olvadáspontjuk és összetételük',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Melyik országban vezették be először a sikeres betétdíjas rendszereket?',
      answers: JSON.stringify(['Brazília', 'Egyiptom', 'India', 'Németország és a skandináv országok']),
      correct: 'Németország és a skandináv országok',
      funfact: 'Németországban a PET-palackok visszaváltási aránya a betétdíjnak köszönhetően meghaladja a 95%-ot.',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi az a "szürkevíz"?',
      answers: JSON.stringify(['Veszélyes ipari szennyvíz', 'A világtengerek sós vize', 'A tetőről lefolyó esővíz', 'Újrahasznosítható háztartási víz']),
      correct: 'Újrahasznosítható háztartási víz',
      funfact: 'A szürkevíz használatával egy átlagos háztartás vízfogyasztása akár 30-50%-kal is csökkenthető.',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a teendő a használt sütőolajjal?',
      answers: JSON.stringify(['A konyhai mosogatóba öntés', 'A lakás vécéjébe való öntés', 'Állati takarmányba keverés', 'Leadás kijelölt gyűjtőponton']),
      correct: 'Leadás kijelölt gyűjtőponton',
      funfact: 'Egyetlen liter használt sütőolaj akár egymillió liter élővizet is elszennyezhet, ha a lefolyóba kerül.',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mekkora része hasznosítható újra egy átlagos mobiltelefonnak?',
      answers: JSON.stringify(['Kevesebb mint 10%', 'Maximum 25%-a', 'Pontosan a fele', 'Akár 80-90%-a']),
      correct: 'Akár 80-90%-a',
      funfact: 'Egy tonna régi mobiltelefonból több aranyat lehet kinyerni, mint egy tonna aranyércből.',
      history: '',
    },

    // 3. Vízvédelem
    {
      title: 'Vízvédelem',
      question: 'A Föld vízkészletének körülbelül hány százaléka édesvíz?',
      answers: JSON.stringify(['50%', '25%', '10%', 'Kevesebb mint 3%']),
      correct: 'Kevesebb mint 3%',
      funfact: 'Ennek az édesvíznek is nagy része (kb. 70%) jégtakarókban és gleccserekben van megkötve.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'A legnagyobb édesvíz-felhasználó ágazat a világon?',
      answers: JSON.stringify(['Ipar', 'Lakossági fogyasztás', 'Turizmus', 'Mezőgazdaság (öntözés)']),
      correct: 'Mezőgazdaság (öntözés)',
      funfact: 'A mezőgazdaság felelős a globális édesvíz-felhasználás körülbelül 70%-áért.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit nevezünk eutrofizációnak?',
      answers: JSON.stringify(['A víz természetes elpárolgását', 'A tavak jégpáncéljának hízását', 'A halállomány szezonális mozgását', 'Vizek túlzott tápanyagdúsulását']),
      correct: 'Vizek túlzott tápanyagdúsulását',
      funfact: 'A folyamat gyakran a műtrágyák bemosódása miatt alakul ki, és a halak pusztulásához vezethet.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Miért káros a mikroműanyag a vizekben?',
      answers: JSON.stringify(['Esztétikailag rontja a víz látványát', 'Fizikailag lassítja a természetes hullámzást', 'Akadályozza a szabadidős hajózást', 'Bekerül az élelmiszerláncba']),
      correct: 'Bekerül az élelmiszerláncba',
      funfact: 'Becslések szerint egy átlagos ember hetente egy bankkártyányi súlyú mikroműanyagot fogyaszt el a vízzel és ételekkel.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Melyik tó a világ legmélyebb édesvizű tava?',
      answers: JSON.stringify(['Balaton', 'Viktória-tó', 'Felső-tó', 'Bajkál-tó']),
      correct: 'Bajkál-tó',
      funfact: 'A Bajkál-tóban található a Föld folyékony édesvízkészletének körülbelül 20%-a.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Hogyan takarékoskodhatunk a legtöbb vízzel a fürdőszobában?',
      answers: JSON.stringify(['Ha gyakrabban mosunk kezet', 'Ha forróbb vizet használunk', 'Ha sokat mosunk fél töltettel', 'Ha fürdés helyett rövid zuhanyzást választunk']),
      correct: 'Ha fürdés helyett rövid zuhanyzást választunk',
      funfact: 'Egy kádas fürdéshez 120-150 liter víz kell, egy 5 perces zuhanyzáshoz viszont csak 40-50 liter.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a célja a szennyvíztisztításnak?',
      answers: JSON.stringify(['A víz sótartalmának növelése', 'Nemesfémek kinyerése a vízből', 'Desztillált ivóvíz előállítása', 'A szennyeződések eltávolítása']),
      correct: 'A szennyeződések eltávolítása',
      funfact: 'A modern tisztítótelepeken mikroorganizmusok "eszik meg" a vízben lévő szerves szennyeződéseket.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi az a vízlépcső vagy gát negatív környezeti hatása?',
      answers: JSON.stringify(['Túl sok elektromos áramot termel', 'Túlságosan szépíti a természetet', 'Segíti a halállomány szabad mozgását', 'Megbontja a folyó ökoszisztémáját']),
      correct: 'Megbontja a folyó ökoszisztémáját',
      funfact: 'Sok helyen már speciális "hallépcsőket" építenek, hogy a halak átjuthassanak a gátakon.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit jelent a "vízlábnyom" kifejezés?',
      answers: JSON.stringify(['A part menti fövenyen hagyott nyomok', 'A víztestek aktuális mélységmutatója', 'Az egyéni úszóteljesítmény mérőszáma', 'A termékekhez elhasznált vízmennyiség']),
      correct: 'A termékekhez elhasznált vízmennyiség',
      funfact: 'Egyetlen pamutpóló előállításához például körülbelül 2500-2700 liter vízre van szükség.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Hol található a legtöbb édesvíz a Földön?',
      answers: JSON.stringify(['A világ összes folyójában', 'A nagy kontinentális tavakban', 'A légkörben pára formájában', 'Sarki jégbe és gleccserekbe zárva']),
      correct: 'Sarki jégbe és gleccserekbe zárva',
      funfact: 'Sajnos a klímaváltozás miatt ezek a jégtömegek olvadnak, és sós óceánvízzé válnak, ami visszafordíthatatlan veszteség.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a legnagyobb szennyező forrás az óceánokban?',
      answers: JSON.stringify(['Több évszázada elsüllyedt hajók', 'A tengeri emlősök természetes ürüléke', 'A tenger alatti vulkánok hamuja', 'Szárazföldről bejutó műanyag és vegyi anyag']),
      correct: 'Szárazföldről bejutó műanyag és vegyi anyag',
      funfact: 'Az óceáni szemétszigetek (pl. a Nagy Csendes-óceáni Szemétsziget) területe többszöröse Magyarországénak.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Miért nem szabad gyógyszereket a vécébe dobni?',
      answers: JSON.stringify(['A vezetékrendszer eldugulását okozza', 'Túlságosan költséges a gyógyszerpazarlás', 'Jelentősen megváltoztatja a víz ízét', 'Károsítja a vízi élőlényeket']),
      correct: 'Károsítja a vízi élőlényeket',
      funfact: 'A vízbe kerülő hormonok és antibiotikumok megváltoztathatják a halak viselkedését és szaporodását.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Melyik tenger sósabb: a Holt-tenger vagy a Balti-tenger?',
      answers: JSON.stringify(['Egyforma a sótartalmuk', 'A Balti-tenger', 'Egyik sem sós', 'A Holt-tenger (extrém magas sótartalommal)']),
      correct: 'A Holt-tenger (extrém magas sótartalommal)',
      funfact: 'A Holt-tengerben a sótartalom kb. 34%, ami olyan sűrűvé teszi a vizet, hogy az ember lebeg rajta.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit jelent a "víz stressz" fogalma?',
      answers: JSON.stringify(['A folyók sebességének hirtelen növekedése', 'A halállományt érő környezeti ártalom', 'A csapadékmentes napok számának növekedése', 'Amikor a vízigény meghaladja a forrásokat']),
      correct: 'Amikor a vízigény meghaladja a forrásokat',
      funfact: 'Jelenleg a világ lakosságának kb. egynegyede él vízhiányos területeken.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Milyen módon segítik az erdők a víz védelmét?',
      answers: JSON.stringify(['Elszívják a felesleges talajvizet', 'Teljesen megállítják a folyók folyását', 'Párologtatásukkal növelik a sós víz arányát', 'Szűrik a csapadékot és gátolják az eróziót']),
      correct: 'Szűrik a csapadékot és gátolják az eróziót',
      funfact: 'Az erdő talaja úgy működik, mint egy óriási szivacs, ami visszatartja és megtisztítja a vizet.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mennyi vizet használ el egy átlagos nyugati ember naponta közvetlenül?',
      answers: JSON.stringify(['5 litert', '10 litert', '50 litert', '120-150 litert']),
      correct: '120-150 litert',
      funfact: 'Ennek a vízmennyiségnek a jelentős része a vécéöblítésre és a fürdésre megy el, nem pedig ivásra.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a "Nagy Csendes-óceáni Szemétsziget"?',
      answers: JSON.stringify(['Egy új, mesterséges üdülősziget', 'Szigetcsoport a Csendes-óceánon', 'Hatalmas úszó sarki jégtábla', 'Hatalmas méretű úszó hulladékmező']),
      correct: 'Hatalmas méretű úszó hulladékmező',
      funfact: 'A "sziget" valójában nem szilárd föld, hanem egy hatalmas levest állagú terület, ami tele van apró műanyagdarabokkal.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit nevezünk talajvíznek?',
      answers: JSON.stringify(['A felszínen kialakuló pocsolyákat', 'Keresztülfolyó öntözővíz-hálózatot', 'A világtengerek és óceánok vizét', 'A föld felszíne alatt található vizet']),
      correct: 'A föld felszíne alatt található vizet',
      funfact: 'A talajvíz szintje az utóbbi években sok helyen drasztikusan csökkent a túlzott öntözés és a kevés csapadék miatt.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a deszalinizáció?',
      answers: JSON.stringify(['A víz mesterséges fagyasztása', 'A víz vitaminokkal való dúsítása', 'A víz fertőtlenítő klórozása', 'Ivóvíz előállítása tengervízből']),
      correct: 'Ivóvíz előállítása tengervízből',
      funfact: 'Bár drága és energiaigényes folyamat, sok közel-keleti ország számára ez az egyetlen mód az ivóvíz biztosítására.',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Melyik nemzetközi nap hívja fel a figyelmet a víz fontosságára?',
      answers: JSON.stringify(['Április 1.', 'Január 1.', 'Május 1.', 'Március 22. (Víz Világnapja)']),
      correct: 'Március 22. (Víz Világnapja)',
      funfact: 'A Víz Világnapját 1993 óta tartják meg az ENSZ kezdeményezésére.',
      history: '',
    },

    // 4. Erdők
    {
      title: 'Erdők',
      question: 'A Föld szárazföldi területének körülbelül mekkora részét borítják erdők?',
      answers: JSON.stringify(['5%', '10%', '50%', 'Kb. 31%']),
      correct: 'Kb. 31%',
      funfact: 'Az erdők aránya folyamatosan csökken, de egyes országokban a tudatos erdőtelepítésnek köszönhetően nőni kezdett.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik erdőtípust nevezzük a "Föld tüdejének"?',
      answers: JSON.stringify(['A szibériai tajgát', 'A magyarországi bükkösöket', 'A kanadai fenyőerdőket', 'Az Amazonas-medence trópusi esőerdőit']),
      correct: 'Az Amazonas-medence trópusi esőerdőit',
      funfact: 'A trópusi esőerdők nemcsak oxigént termelnek, hanem a világ biodiverzitásának több mint felét is magukba foglalják.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a fotoszintézis fő mellékterméke, ami létfontosságú az embernek?',
      answers: JSON.stringify(['Szén-dioxid', 'Nitrogén', 'Metán', 'Oxigén']),
      correct: 'Oxigén',
      funfact: 'Egyetlen nagy lombú fa egyetlen nap alatt annyi oxigént termel, amennyi két felnőtt embernek elég.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi az erdőirtás egyik legfőbb oka világszerte?',
      answers: JSON.stringify(['Gyalogtúrák és turizmus', 'Szabályozott vadgazdálkodás', 'Növények természetes öregedése', 'Mezőgazdasági terület szerzése']),
      correct: 'Mezőgazdasági terület szerzése',
      funfact: 'Percenként körülbelül 30 futballpályányi erdő tűnik el a Földön az erdőirtások miatt.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit nevezünk őserdőnek?',
      answers: JSON.stringify(['Ahol régen dinoszauruszok éltek', 'Minden legalább 50 éves erdőt', 'Ember által telepített fenyveseket', 'Természetes, érintetlen erdőt']),
      correct: 'Természetes, érintetlen erdőt',
      funfact: 'Az őserdőkben sokkal több a holtfa, ami alapvető fontosságú a ritka bogárfajok számára.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Hogyan védekeznek az erdők a globális felmelegedés ellen?',
      answers: JSON.stringify(['Aktívan hűtik a föld magját', 'Visszaverik a napsugárzást', 'Fizikailag megállítják a szelet', 'Szén-dioxidot kötnek meg']),
      correct: 'Szén-dioxidot kötnek meg',
      funfact: 'A fák nemcsak a törzsükben, hanem a gyökérzetükben és a talajban is hatalmas mennyiségű szenet raktároznak.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik ország rendelkezik a legnagyobb erdőterülettel a világon?',
      answers: JSON.stringify(['Kína', 'USA', 'Brazília', 'Oroszország']),
      correct: 'Oroszország',
      funfact: 'Az orosz tajga a világ legnagyobb egybefüggő erdősége, és hatalmas szén-dioxid-elnyelő kapacitással bír.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit jelent az erdőfelújítás?',
      answers: JSON.stringify(['A beteg fák törzsének kezelését', 'Turistaútvonalak kiépítését', 'Kidőlt fatörzsek rendszeres ürítését', 'Új erdő létrehozását a régi helyén']),
      correct: 'Új erdő létrehozását a régi helyén',
      funfact: 'Sok helyen drónokkal szórják ki a magokat, hogy gyorsabban és hatékonyabban újítsák fel a leégett erdőket.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi az erdők szerepe a talajvédelemben?',
      answers: JSON.stringify(['Elszívják a talaj tápanyagait', 'Növelik a talajfelszín hőmérsékletét', 'Gátolják a talaj hasznos fagyását', 'Megkötik a talajt a gyökereikkel']),
      correct: 'Megkötik a talajt a gyökereikkel',
      funfact: 'Erdő nélküli domboldalakon egyetlen heves esőzés is képes méterekkel lejjebb mosni a termőtalajt.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a pálmaolaj-termelés fő problémája az erdők szempontjából?',
      answers: JSON.stringify(['A pálmák túlzott magassága', 'A pálmák extrém vízigénye', 'A kész termék élettani hatásai', 'Hatalmas erdőterületek felégetése']),
      correct: 'Hatalmas erdőterületek felégetése',
      funfact: 'A pálmaolaj-ültetvények terjedése miatt az orangutánok az egyik legveszélyeztetettebb fajtájává váltak a majmoknak.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik kontinensen található a legtöbb trópusi esőerdő?',
      answers: JSON.stringify(['Európa', 'Ausztrália', 'Antarktisz', 'Dél-Amerika']),
      correct: 'Dél-Amerika',
      funfact: 'Az Amazonas folyó és esőerdője olyan hatalmas, hogy több víz érkezik belőle az óceánba, mint a következő hét legnagyobb folyóból összesen.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a holtfa szerepe az erdőben?',
      answers: JSON.stringify(['Veszélyes, el kell távolítani', 'Rontja a táj esztétikáját', 'Növeli az erdőtűz kockázatát', 'Fontos élőhely és táplálék']),
      correct: 'Fontos élőhely és táplálék',
      funfact: 'A holtfa lebomlása során tápanyagok kerülnek vissza a talajba, ami az új generációs fák növekedését segíti.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik fa a leggyakoribb erdőalkotó faj Magyarországon?',
      answers: JSON.stringify(['Fenyő', 'Nyír', 'Akác', 'Kocsánytalan tölgy és bükk']),
      correct: 'Kocsánytalan tölgy és bükk',
      funfact: 'A tölgyerdőknek rendkívül gazdag az élőviláguk; több száz különböző rovarfaj élhet egyetlen fán.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit jelent az FSC tanúsítvány a papírtermékeken vagy bútorokon?',
      answers: JSON.stringify(['Hogy a termék nagyon olcsó', 'Hogy a terméket repülővel hozták', 'Hogy a termék vízálló', 'Hogy a fa alapanyag felelős és fenntartható erdőgazdálkodásból származik']),
      correct: 'Hogy a fa alapanyag felelős és fenntartható erdőgazdálkodásból származik',
      funfact: 'Az FSC címke segít a vásárlóknak, hogy ne járuljanak hozzá az illegális fakitermeléshez és az esőerdők pusztításához.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Milyen hatással van az erdőtűz a környezetre?',
      answers: JSON.stringify(['Csak pozitív hatása van', 'Csökkenti a szén-dioxid szintet', 'Megállítja a globális felmelegedést', 'Hatalmas mennyiségű szén-dioxidot szabadít fel és rombolja az élőhelyeket']),
      correct: 'Hatalmas mennyiségű szén-dioxidot szabadít fel és rombolja az élőhelyeket',
      funfact: 'Bár egyes erdőtípusoknak (pl. bizonyos fenyveseknek) szükségük van a tűzre a megújuláshoz, a gyakoribbá váló intenzív tüzek súlyos károkat okoznak.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi az erdő szintezettségének sorrendje alulról felfelé?',
      answers: JSON.stringify(['Lombkoronaszint, cserjeszint, gyepszint', 'Csak fakorona létezik', 'Gyepszint, lombkoronaszint, cserjeszint', 'Mohaszint, gyepszint, cserjeszint, lombkoronaszint']),
      correct: 'Mohaszint, gyepszint, cserjeszint, lombkoronaszint',
      funfact: 'A szintezettség lehetővé teszi, hogy különböző igényű növények és állatok éljenek egymás mellett ugyanazon a területen.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Miért fontosak az erdők a csapadékképződésben?',
      answers: JSON.stringify(['Mert vonzzák a mágneses hullámokat', 'Mert megállítják a felhőket', 'Mert hideget sugároznak', 'A párologtatásuk révén nedvességet juttatnak a levegőbe, ami segíti az esők kialakulását']),
      correct: 'A párologtatásuk révén nedvességet juttatnak a levegőbe, ami segíti az esők kialakulását',
      funfact: 'Egyetlen nagy fa naponta akár több száz liter vizet is elpárologtathat a leveleiről.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik madárfaj az erdők "doktora", mert megszabadítja a fákat a kártevőktől?',
      answers: JSON.stringify(['Sas', 'Veréb', 'Bagoly', 'Harkály']),
      correct: 'Harkály',
      funfact: 'A harkályok nemcsak esznek, hanem odúkat is készítenek, amiket később más madarak és emlősök is használnak.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a tarvágás?',
      answers: JSON.stringify(['A fák ágainak levágása', 'A beteg fák kivágása', 'Csak a gyomok kiirtása', 'Egy adott területen az összes fa egyidejű kitermelése']),
      correct: 'Egy adott területen az összes fa egyidejű kitermelése',
      funfact: 'A modern erdőgazdálkodás próbálja kerülni a tarvágást, és inkább a szálaló vágást alkalmazza, ami kíméletesebb a talajnak.',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit nevezünk városi erdőnek?',
      answers: JSON.stringify(['A virágcserepeket az erkélyen', 'A múzeumok növényeit', 'A műanyag fákat a plázákban', 'A városi környezetben tudatosan fenntartott, erdő jellegű zöldterületeket']),
      correct: 'A városi környezetben tudatosan fenntartott, erdő jellegű zöldterületeket',
      funfact: 'A városi erdők csökkentik a hőszigethatást és jelentősen javítják a városlakók mentális egészségét.',
      history: '',
    },
  ];

  for (const q of questions) {
    const { history, ...data } = q as any;
    await prisma.feladatok.upsert({
      where: {
        id: questions.indexOf(q) + 1,
      },
      update: data,
      create: data,
    });
  }

  console.log(`✅ Seeded ${questions.length} questions.`);
}
