import { PrismaClient } from '@prisma/client';

export async function seedQuestions(prisma: PrismaClient) {
  const questions = [
    // 1. Alapfogalmak
    {
      title: 'Alapfogalmak',
      question: 'Mi a környezetvédelem elsődleges célja?',
      answers: JSON.stringify(['Az ipari termelés maximalizálása', 'Kizárólag az állatok védelme', 'Az emberi kényelem mindenáron való kiszolgálása', 'Az élővilág és az emberi életfeltételek megőrzése']),
      correct: 'Az élővilág és az emberi életfeltételek megőrzése',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent az "ökológiai lábnyom" kifejezés?',
      answers: JSON.stringify(['Az erdőkben hagyott fizikai lábnyomokat', 'Egy ország GDP-jének növekedését', 'A cipőgyártás környezeti hatását', 'Az erőforrások mennyiségét, amire egy embernek vagy társadalomnak szüksége van az életmódja fenntartásához']),
      correct: 'Az erőforrások mennyiségét, amire egy embernek vagy társadalomnak szüksége van az életmódja fenntartásához',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Melyik gáz a felelős leginkább az üvegházhatás fokozódásáért az emberi tevékenység révén?',
      answers: JSON.stringify(['Oxigén', 'Hidrogén', 'Argon', 'Szén-dioxid']),
      correct: 'Szén-dioxid',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a fenntartható fejlődés lényege?',
      answers: JSON.stringify(['Csak a jelen generáció igényeinek kielégítése', 'A technológiai fejlődés leállítása', 'A természet teljes érintetlensége', 'A jelen igényeinek kielégítése úgy, hogy az ne veszélyeztesse a jövő generációk szükségleteit']),
      correct: 'A jelen igényeinek kielégítése úgy, hogy az ne veszélyeztesse a jövő generációk szükségleteit',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit nevezünk biodiverzitásnak?',
      answers: JSON.stringify(['A különböző technológiák sokszínűségét', 'Az elektromos autók elterjedését', 'A szelektív hulladékgyűjtést', 'Az élővilág, a fajok és az ökoszisztémák sokféleségét']),
      correct: 'Az élővilág, a fajok és az ökoszisztémák sokféleségét',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a globális felmelegedés egyik fő következménye?',
      answers: JSON.stringify(['Az óceánok szintjének csökkenése', 'A sarki jégsapkák növekedése', 'A vulkáni aktivitás megszűnése', 'A szélsőséges időjárási események gyakoriságának növekedése']),
      correct: 'A szélsőséges időjárási események gyakoriságának növekedése',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a célja a 2015-ös Párizsi Megállapodásnak?',
      answers: JSON.stringify(['Az űrkutatás támogatása', 'A világgazdaság központosítása', 'A műanyaggyártás betiltása 2020-ig', 'A globális átlaghőmérséklet emelkedésének 2 Celsius-fok alatt tartása']),
      correct: 'A globális átlaghőmérséklet emelkedésének 2 Celsius-fok alatt tartása',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Milyen típusú erőforrás a napenergia?',
      answers: JSON.stringify(['Fosszilis', 'Véges', 'Kimerülő', 'Megújuló']),
      correct: 'Megújuló',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit mér az ökoszisztéma-szolgáltatás?',
      answers: JSON.stringify(['A környezetvédelmi hatóságok munkáját', 'A napelemek hatékonyságát', 'Az állatkertek látogatottságát', 'A természet által az emberiségnek nyújtott hasznokat (pl. beporzás, tiszta levegő)']),
      correct: 'A természet által az emberiségnek nyújtott hasznokat (pl. beporzás, tiszta levegő)',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent a dekarbonizáció?',
      answers: JSON.stringify(['A szénbányászat növelését', 'A gyémántkészítés folyamatát', 'A növények szénfelvételének gátlását', 'Az üvegházhatású gázok kibocsátásának csökkentését vagy megszüntetését']),
      correct: 'Az üvegházhatású gázok kibocsátásának csökkentését vagy megszüntetését',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi az invazív faj fogalma?',
      answers: JSON.stringify(['Egy veszélyeztetett őshonos állat', 'Egy kihalófélben lévő növény', 'Mesterségesen létrehozott hibrid faj', 'Olyan idegenhonos faj, amely megtelepedése után károsítja az új környezetét']),
      correct: 'Olyan idegenhonos faj, amely megtelepedése után károsítja az új környezetét',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Melyik szervezet az ENSZ legfőbb környezetvédelmi szerve?',
      answers: JSON.stringify(['NASA', 'WHO', 'UNICEF', 'UNEP']),
      correct: 'UNEP',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi az ózonréteg feladata?',
      answers: JSON.stringify(['A szén-dioxid elnyelése', 'A felhőképződés segítése', 'A levegő lehűtése', 'A Nap káros ultraibolya (UV) sugárzásának elnyelése']),
      correct: 'A Nap káros ultraibolya (UV) sugárzásának elnyelése',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit nevezünk túlfogyasztási napnak?',
      answers: JSON.stringify(['A karácsonyi bevásárlási időszakot', 'Amikor a boltokban kiárusítás van', 'Az év utolsó napját', 'Azt a dátumot, amikor az emberiség elhasználja a Föld adott évre vonatkozó erőforrásait']),
      correct: 'Azt a dátumot, amikor az emberiség elhasználja a Föld adott évre vonatkozó erőforrásait',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a megújuló energiaforrások egyik legnagyobb előnye?',
      answers: JSON.stringify(['Hogy drágábbak a szénnél', 'Hogy mindenhol egyformán elérhetőek', 'Hogy nem igényelnek karbantartást', 'Hogy üzemeltetésük során alacsony vagy nulla a károsanyag-kibocsátásuk']),
      correct: 'Hogy üzemeltetésük során alacsony vagy nulla a károsanyag-kibocsátásuk',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent a környezetterhelési díj?',
      answers: JSON.stringify(['A szemétszállítási díjat', 'A környezetbarát termékek adóját', 'Egy önkéntes adományt a Greenpeace-nek', 'A környezethasználó által fizetett díjat a környezet igénybevételéért']),
      correct: 'A környezethasználó által fizetett díjat a környezet igénybevételéért',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a "zöldmosás" (greenwashing)?',
      answers: JSON.stringify(['A ruhák környezetbarát mosása', 'A napelemek tisztítása vízzel', 'A fák lemosása az erdőtüzek után', 'Egy vállalat megtévesztő stratégiája, amellyel környezetbarátabbnak tünteti fel magát a valóságnál']),
      correct: 'Egy vállalat megtévesztő stratégiája, amellyel környezetbarátabbnak tünteti fel magát a valóságnál',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Melyik szektor felelős globálisan a legtöbb üvegházhatású gáz kibocsátásáért?',
      answers: JSON.stringify(['Szemétszállítás', 'Divatipar', 'Turizmus', 'Energiaellátás (villamosenergia- és hőtermelés)']),
      correct: 'Energiaellátás (villamosenergia- és hőtermelés)',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mi a biomassza?',
      answers: JSON.stringify(['Műanyag hulladék halmaza', 'Ásványi kőzetek összessége', 'Fémhulladék újrahasznosításra', 'Biológiai úton lebomló szerves anyagok összessége']),
      correct: 'Biológiai úton lebomló szerves anyagok összessége',
      funfact: '',
      history: '',
    },
    {
      title: 'Alapfogalmak',
      question: 'Mit jelent az ökocímke a termékeken?',
      answers: JSON.stringify(['Hogy a termék nagyon drága', 'Hogy a terméket külföldről hozták', 'Hogy a termék zöld színű', 'Hogy a termék életciklusa során bizonyítottan kisebb terhelést jelent a környezetre']),
      correct: 'Hogy a termék életciklusa során bizonyítottan kisebb terhelést jelent a környezetre',
      funfact: '',
      history: '',
    },

    // 2. Újrahasznosítás
    {
      title: 'Újrahasznosítás',
      question: 'Melyik anyag hasznosítható újra szinte végtelen alkalommal minőségromlás nélkül?',
      answers: JSON.stringify(['Papír', 'Műanyag', 'Textil', 'Üveg']),
      correct: 'Üveg',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Milyen színű gyűjtőedénybe kell dobni a tiszta papírhulladékot Magyarországon?',
      answers: JSON.stringify(['Sárga', 'Szürke', 'Fehér', 'Kék']),
      correct: 'Kék',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a szelektív hulladékgyűjtés legfontosabb szabálya a műanyag flakonoknál?',
      answers: JSON.stringify(['Tele kell hagyni őket vízzel', 'Nem szabad őket összenyomni', 'Le kell vágni az aljukat', 'Ki kell öblíteni és laposra kell taposni őket']),
      correct: 'Ki kell öblíteni és laposra kell taposni őket',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi történik a papírral minden egyes újrahasznosítási ciklus során?',
      answers: JSON.stringify(['Fehéredik', 'Egyre vastagabb lesz', 'Megszínesedik', 'A cellulózrostok rövidülnek és gyengülnek']),
      correct: 'A cellulózrostok rövidülnek és gyengülnek',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi az újrahasznosítás (recycle) és az újrafelhasználás (reuse) közötti különbség?',
      answers: JSON.stringify(['Nincs különbség a kettő között', 'Az újrahasznosítás otthon történik, az újrafelhasználás gyárban', 'Az újrahasznosítás drágább, mint az újrafelhasználás', 'Az újrafelhasználásnál az tárgy eredeti formájában marad, az újrahasznosításnál alapanyaggá alakítják']),
      correct: 'Az újrafelhasználásnál az tárgy eredeti formájában marad, az újrahasznosításnál alapanyaggá alakítják',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Melyik hulladékfajtát nevezzük "e-hulladéknak"?',
      answers: JSON.stringify(['Élelmiszer maradék', 'Elhasznált papír zsebkendő', 'Építési törmelék', 'Elromlott elektronikai berendezések']),
      correct: 'Elromlott elektronikai berendezések',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Miért veszélyes az elem a rendes szemétben?',
      answers: JSON.stringify(['Mert büdös lesz tőle a kuka', 'Mert felrobbanhat a szemetesautóban', 'Mert elfoglalja a helyet a papírtól', 'Mert nehézfémeket tartalmaz, amelyek kimosódva mérgezik a talajt és a vizet']),
      correct: 'Mert nehézfémeket tartalmaz, amelyek kimosódva mérgezik a talajt és a vizet',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a komposztálás fő célja?',
      answers: JSON.stringify(['A műanyag lebontása', 'A fémek tisztítása', 'A papír megsemmisítése', 'A szerves hulladék tápanyagban gazdag földdé alakítása']),
      correct: 'A szerves hulladék tápanyagban gazdag földdé alakítása',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Körülbelül mennyi idő alatt bomlik le egy műanyag palack a természetben?',
      answers: JSON.stringify(['1-2 év', '10-20 év', '100-150 év', '450-500 év (vagy soha teljesen)']),
      correct: '450-500 év (vagy soha teljesen)',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a sárga szelektív kuka elsődleges tartalma Magyarországon?',
      answers: JSON.stringify(['Csak üveg', 'Csak újságpapír', 'Csak ételmaradék', 'Műanyag és gyakran fém csomagolási hulladék']),
      correct: 'Műanyag és gyakran fém csomagolási hulladék',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a cirkuláris (körforgásos) gazdaság alapelve?',
      answers: JSON.stringify(['Minden terméket el kell égetni', 'A termékeket kör alakúra kell tervezni', 'A gazdasági növekedés megállítása', 'A hulladék keletkezésének minimalizálása és az anyagok körforgásban tartása']),
      correct: 'A hulladék keletkezésének minimalizálása és az anyagok körforgásban tartása',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Milyen hulladékot nem szabad a komposztba tenni?',
      answers: JSON.stringify(['Tojáshéj', 'Kávézacc', 'Száraz falevél', 'Hús- és tejtermék maradék']),
      correct: 'Hús- és tejtermék maradék',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mit jelent a "downcycling" kifejezés?',
      answers: JSON.stringify(['A biciklik újrahasznosítását', 'Az anyagok eredeti minőségben való megőrzését', 'Az újrahasznosítás árának csökkentését', 'Az alapanyag olyan feldolgozását, amelynek során az alacsonyabb minőségű lesz (pl. írópapírból tojástartó)']),
      correct: 'Az alapanyag olyan feldolgozását, amelynek során az alacsonyabb minőségű lesz (pl. írópapírból tojástartó)',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi az alumíniumdobozok újrahasznosításának legnagyobb előnye?',
      answers: JSON.stringify(['Hogy szebbek lesznek tőle a dobozok', 'Hogy könnyebb lesz az anyaguk', 'Hogy nem kell hozzá víz', 'Az új alumínium előállításához képest 95%-os energiamegtakarítást jelent']),
      correct: 'Az új alumínium előállításához képest 95%-os energiamegtakarítást jelent',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Hova kell vinni a használt gumiabroncsokat?',
      answers: JSON.stringify(['A kommunális kukába', 'Az erdő szélére', 'A papírgyűjtőbe', 'Hulladékudvarba vagy gumiabroncs-szervizbe']),
      correct: 'Hulladékudvarba vagy gumiabroncs-szervizbe',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Miért nem dobható a tükör vagy a hőálló üveg a szelektív üveggyűjtőbe?',
      answers: JSON.stringify(['Mert túl nehezek', 'Mert más a színük', 'Mert babonából nem szabad', 'Mert más az olvadáspontjuk és az összetételük, mint az öblösüvegeké']),
      correct: 'Mert más az olvadáspontjuk és az összetételük, mint az öblösüvegeké',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Melyik országban vezették be először a sikeres betétdíjas rendszereket?',
      answers: JSON.stringify(['Brazília', 'Egyiptom', 'India', 'Németország és a skandináv országok']),
      correct: 'Németország és a skandináv országok',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi az a "szürkevíz"?',
      answers: JSON.stringify(['Szennyezett ipari víz', 'A tenger vize', 'Esővíz, ami a tetőről folyik le', 'A háztartásokban keletkező, viszonylag tiszta szennyvíz (pl. zuhanyzásból), ami újra felhasználható (pl. öblítésre)']),
      correct: 'A háztartásokban keletkező, viszonylag tiszta szennyvíz (pl. zuhanyzásból), ami újra felhasználható (pl. öblítésre)',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mi a teendő a használt sütőolajjal?',
      answers: JSON.stringify(['Ki kell önteni a mosogatóba', 'Ki kell önteni a vécébe', 'Be kell keverni a kutyatápba', 'Le kell adni kijelölt gyűjtőpontokon (pl. benzinkutak, hulladékudvarok)']),
      correct: 'Le kell adni kijelölt gyűjtőpontokon (pl. benzinkutak, hulladékudvarok)',
      funfact: '',
      history: '',
    },
    {
      title: 'Újrahasznosítás',
      question: 'Mekkora része hasznosítható újra egy átlagos mobiltelefonnak?',
      answers: JSON.stringify(['5%', '20%', '50%', 'Akár 80-90%-a (fémek, műanyagok, ritka földfémek)']),
      correct: 'Akár 80-90%-a (fémek, műanyagok, ritka földfémek)',
      funfact: '',
      history: '',
    },

    // 3. Vízvédelem
    {
      title: 'Vízvédelem',
      question: 'A Föld vízkészletének körülbelül hány százaléka édesvíz?',
      answers: JSON.stringify(['50%', '25%', '10%', 'Kevesebb mint 3%']),
      correct: 'Kevesebb mint 3%',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'A legnagyobb édesvíz-felhasználó ágazat a világon?',
      answers: JSON.stringify(['Ipar', 'Lakossági fogyasztás', 'Turizmus', 'Mezőgazdaság (öntözés)']),
      correct: 'Mezőgazdaság (öntözés)',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit nevezünk eutrofizációnak?',
      answers: JSON.stringify(['A víz elpárolgását', 'A víz megfagyását', 'A halak vándorlását', 'A vizek tápanyagokkal való túlzott feldúsulását, ami algásodáshoz és oxigénhiányhoz vezet']),
      correct: 'A vizek tápanyagokkal való túlzott feldúsulását, ami algásodáshoz és oxigénhiányhoz vezet',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Miért káros a mikroműanyag a vizekben?',
      answers: JSON.stringify(['Mert színesebbé teszi a vizet', 'Mert lassítja a hullámzást', 'Mert gátolja a hajózást', 'Mert bekerül a táplálékláncba és mérgező anyagokat köt meg']),
      correct: 'Mert bekerül a táplálékláncba és mérgező anyagokat köt meg',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Melyik tó a világ legmélyebb édesvizű tava?',
      answers: JSON.stringify(['Balaton', 'Viktória-tó', 'Felső-tó', 'Bajkál-tó']),
      correct: 'Bajkál-tó',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Hogyan takarékoskodhatunk a legtöbb vízzel a fürdőszobában?',
      answers: JSON.stringify(['Ha gyakrabban mosunk kezet', 'Ha forróbb vizet használunk', 'Ha sokat mosunk fél töltettel', 'Ha fürdés helyett rövid zuhanyzást választunk']),
      correct: 'Ha fürdés helyett rövid zuhanyzást választunk',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a célja a szennyvíztisztításnak?',
      answers: JSON.stringify(['Hogy a vizet sósabbá tegyék', 'Hogy kinyerjék belőle az aranyat', 'Hogy desztillált vizet készítsenek', 'Hogy eltávolítsák a szennyeződéseket, mielőtt a víz visszakerül a természetbe']),
      correct: 'Hogy eltávolítsák a szennyeződéseket, mielőtt a víz visszakerül a természetbe',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi az a vízlépcső vagy gát negatív környezeti hatása?',
      answers: JSON.stringify(['Túl sok áramot termel', 'Szebbé teszi a tájat', 'Segíti a halak mozgását', 'Megváltoztatja a folyó ökoszisztémáját és gátolja a hordalék vándorlását']),
      correct: 'Megváltoztatja a folyó ökoszisztémáját és gátolja a hordalék vándorlását',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit jelent a "vízlábnyom" kifejezés?',
      answers: JSON.stringify(['A parton hagyott lábnyomokat', 'A vízmélységet', 'Az úszási sebességet', 'Egy termék előállításához közvetve és közvetlenül felhasznált vízmennyiséget']),
      correct: 'Egy termék előállításához közvetve és közvetlenül felhasznált vízmennyiséget',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Hol található a legtöbb édesvíz a Földön?',
      answers: JSON.stringify(['Folyókban', 'Tavakban', 'A légkörben', 'Gleccserekben és sarki jégsapkákban tárolva']),
      correct: 'Gleccserekben és sarki jégsapkákban tárolva',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a legnagyobb szennyező forrás az óceánokban?',
      answers: JSON.stringify(['Elsüllyedt hajók kincsei', 'A bálnák ürüléke', 'A vulkáni hamu', 'A szárazföldről származó műanyaghulladék és vegyi anyagok']),
      correct: 'A szárazföldről származó műanyaghulladék és vegyi anyagok',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Miért nem szabad gyógyszereket a vécébe dobni?',
      answers: JSON.stringify(['Mert eldugulhat a cső', 'Mert drága a gyógyszer', 'Mert megváltoztatja a víz ízét', 'Mert a szennyvíztisztítók nem tudják teljesen kiszűrni őket, és károsítják a vízi élővilágot']),
      correct: 'Mert a szennyvíztisztítók nem tudják teljesen kiszűrni őket, és károsítják a vízi élővilágot',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Melyik tenger sósabb: a Holt-tenger vagy a Balti-tenger?',
      answers: JSON.stringify(['Egyforma a sótartalmuk', 'A Balti-tenger', 'Egyik sem sós', 'A Holt-tenger (extrém magas sótartalommal)']),
      correct: 'A Holt-tenger (extrém magas sótartalommal)',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit jelent a "víz stressz" fogalma?',
      answers: JSON.stringify(['Amikor a víz túl gyorsan folyik', 'Amikor a halak félnek', 'Amikor túl sok az eső', 'Amikor a vízigény meghaladja a rendelkezésre álló tiszta víz mennyiségét']),
      correct: 'Amikor a vízigény meghaladja a rendelkezésre álló tiszta víz mennyiségét',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Milyen módon segítik az erdők a víz védelmét?',
      answers: JSON.stringify(['Kiszívják az összes vizet a földből', 'Megállítják a folyókat', 'Elpárologtatják az óceánokat', 'Szűrik a csapadékvizet és szabályozzák a lefolyást, megakadályozva az eróziót']),
      correct: 'Szűrik a csapadékvizet és szabályozzák a lefolyást, megakadályozva az eróziót',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mennyi vizet használ el egy átlagos nyugati ember naponta közvetlenül?',
      answers: JSON.stringify(['5 litert', '10 litert', '50 litert', '120-150 litert']),
      correct: '120-150 litert',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a "Nagy Csendes-óceáni Szemétsziget"?',
      answers: JSON.stringify(['Egy új üdülőhely', 'Egy természetes szigetcsoport', 'Egy úszó jéghegy', 'Egy hatalmas kiterjedésű, lebegő műanyaghulladék-koncentráció az óceánban']),
      correct: 'Egy hatalmas kiterjedésű, lebegő műanyaghulladék-koncentráció az óceánban',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mit nevezünk talajvíznek?',
      answers: JSON.stringify(['A pocsolyákat', 'Az öntözővizet', 'A tengervizet', 'A föld felszíne alatt, a kőzetek és szemcsék közötti üregekben található vizet']),
      correct: 'A föld felszíne alatt, a kőzetek és szemcsék közötti üregekben található vizet',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Mi a deszalinizáció?',
      answers: JSON.stringify(['A víz fagyasztása', 'A víz vitaminokkal való dúsítása', 'A víz klórozása', 'A tengervíz lepárlása vagy szűrése ivóvíz előállítása céljából']),
      correct: 'A tengervíz lepárlása vagy szűrése ivóvíz előállítása céljából',
      funfact: '',
      history: '',
    },
    {
      title: 'Vízvédelem',
      question: 'Melyik nemzetközi nap hívja fel a figyelmet a víz fontosságára?',
      answers: JSON.stringify(['Április 1.', 'Január 1.', 'Május 1.', 'Március 22. (Víz Világnapja)']),
      correct: 'Március 22. (Víz Világnapja)',
      funfact: '',
      history: '',
    },

    // 4. Erdők
    {
      title: 'Erdők',
      question: 'A Föld szárazföldi területének körülbelül mekkora részét borítják erdők?',
      answers: JSON.stringify(['5%', '10%', '50%', 'Kb. 31%']),
      correct: 'Kb. 31%',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik erdőtípust nevezzük a "Föld tüdejének"?',
      answers: JSON.stringify(['A szibériai tajgát', 'A magyarországi bükkösöket', 'A kanadai fenyőerdőket', 'Az Amazonas-medence trópusi esőerdőit']),
      correct: 'Az Amazonas-medence trópusi esőerdőit',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a fotoszintézis fő mellékterméke, ami létfontosságú az embernek?',
      answers: JSON.stringify(['Szén-dioxid', 'Nitrogén', 'Metán', 'Oxigén']),
      correct: 'Oxigén',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi az erdőirtás egyik legfőbb oka világszerte?',
      answers: JSON.stringify(['A turisták jelenléte', 'A vadászat', 'A természetes elöregedés', 'A mezőgazdasági területek (pl. marhalegelők, pálmaolaj-ültetvények) növelése']),
      correct: 'A mezőgazdasági területek (pl. marhalegelők, pálmaolaj-ültetvények) növelése',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit nevezünk őserdőnek?',
      answers: JSON.stringify(['Ahol régen dínók éltek', 'Minden erdőt, ami 50 évnél idősebb', 'Az ember által telepített fenyveseket', 'Olyan természetes állapotú erdőt, amelyet az emberi tevékenység nem vagy alig módosított']),
      correct: 'Olyan természetes állapotú erdőt, amelyet az emberi tevékenység nem vagy alig módosított',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Hogyan védekeznek az erdők a globális felmelegedés ellen?',
      answers: JSON.stringify(['Hűtik a föld magját', 'Visszaverik a fényt a leveleikkel', 'Megállítják a szelet', 'Jelentős mennyiségű szén-dioxidot kötnek meg és tárolnak']),
      correct: 'Jelentős mennyiségű szén-dioxidot kötnek meg és tárolnak',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik ország rendelkezik a legnagyobb erdőterülettel a világon?',
      answers: JSON.stringify(['Kína', 'USA', 'Brazília', 'Oroszország']),
      correct: 'Oroszország',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit jelent az erdőfelújítás?',
      answers: JSON.stringify(['A fák lefestését zöldre', 'Az utak építését az erdőben', 'A kidőlt fák elszállítását', 'A kitermelt vagy elpusztult erdő helyén új erdő létrehozását']),
      correct: 'A kitermelt vagy elpusztult erdő helyén új erdő létrehozását',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi az erdők szerepe a talajvédelemben?',
      answers: JSON.stringify(['Elszívják a talaj tápanyagait', 'Növelik a talaj hőmérsékletét', 'Megakadályozzák a talaj megfagyását', 'Gyökérzetükkel megkötik a talajt, megakadályozva az eróziót és a földcsuszamlásokat']),
      correct: 'Gyökérzetükkel megkötik a talajt, megakadályozva az eróziót és a földcsuszamlásokat',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a pálmaolaj-termelés fő problémája az erdők szempontjából?',
      answers: JSON.stringify(['Hogy a pálmák túl magasra nőnek', 'Hogy a pálmák sok vizet isznak', 'Hogy a pálmaolaj nem egészséges', 'Hatalmas trópusi esőerdőket vágnak ki és égetnek fel az ültetvények miatt']),
      correct: 'Hatalmas trópusi esőerdőket vágnak ki és égetnek fel az ültetvények miatt',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik kontinensen található a legtöbb trópusi esőerdő?',
      answers: JSON.stringify(['Európa', 'Ausztrália', 'Antarktisz', 'Dél-Amerika']),
      correct: 'Dél-Amerika',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a holtfa szerepe az erdőben?',
      answers: JSON.stringify(['Nincs szerepe, el kell takarítani', 'Csak rontja az erdő látványát', 'Tűzveszélyes és csak kárt okoz', 'Fontos élőhelyet és táplálékot biztosít számos gombának, rovarnak és madárnak']),
      correct: 'Fontos élőhelyet és táplálékot biztosít számos gombának, rovarnak és madárnak',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik fa a leggyakoribb erdőalkotó faj Magyarországon?',
      answers: JSON.stringify(['Fenyő', 'Nyír', 'Akác', 'Kocsánytalan tölgy és bükk']),
      correct: 'Kocsánytalan tölgy és bükk',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit jelent az FSC tanúsítvány a papírtermékeken vagy bútorokon?',
      answers: JSON.stringify(['Hogy a termék nagyon olcsó', 'Hogy a terméket repülővel hozták', 'Hogy a termék vízálló', 'Hogy a fa alapanyag felelős és fenntartható erdőgazdálkodásból származik']),
      correct: 'Hogy a fa alapanyag felelős és fenntartható erdőgazdálkodásból származik',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Milyen hatással van az erdőtűz a környezetre?',
      answers: JSON.stringify(['Csak pozitív hatása van', 'Csökkenti a szén-dioxid szintet', 'Megállítja a globális felmelegedést', 'Hatalmas mennyiségű szén-dioxidot szabadít fel és rombolja az élőhelyeket']),
      correct: 'Hatalmas mennyiségű szén-dioxidot szabadít fel és rombolja az élőhelyeket',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi az erdő szintezettségének sorrendje alulról felfelé?',
      answers: JSON.stringify(['Lombkoronaszint, cserjeszint, gyepszint', 'Csak fakorona létezik', 'Gyepszint, lombkoronaszint, cserjeszint', 'Mohaszint, gyepszint, cserjeszint, lombkoronaszint']),
      correct: 'Mohaszint, gyepszint, cserjeszint, lombkoronaszint',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Miért fontosak az erdők a csapadékképződésben?',
      answers: JSON.stringify(['Mert vonzzák a mágneses hullámokat', 'Mert megállítják a felhőket', 'Mert hideget sugároznak', 'A párologtatásuk révén nedvességet juttatnak a levegőbe, ami segíti az esők kialakulását']),
      correct: 'A párologtatásuk révén nedvességet juttatnak a levegőbe, ami segíti az esők kialakulását',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Melyik madárfaj az erdők "doktora", mert megszabadítja a fákat a kártevőktől?',
      answers: JSON.stringify(['Sas', 'Veréb', 'Bagoly', 'Harkály']),
      correct: 'Harkály',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mi a tarvágás?',
      answers: JSON.stringify(['A fák ágainak levágása', 'A beteg fák kivágása', 'Csak a gyomok kiirtása', 'Egy adott területen az összes fa egyidejű kitermelése']),
      correct: 'Egy adott területen az összes fa egyidejű kitermelése',
      funfact: '',
      history: '',
    },
    {
      title: 'Erdők',
      question: 'Mit nevezünk városi erdőnek?',
      answers: JSON.stringify(['A virágcserepeket az erkélyen', 'A múzeumok növényeit', 'A műanyag fákat a plázákban', 'A városi környezetben tudatosan fenntartott, erdő jellegű zöldterületeket']),
      correct: 'A városi környezetben tudatosan fenntartott, erdő jellegű zöldterületeket',
      funfact: '',
      history: '',
    },
  ];

  for (const q of questions) {
    const normalizedAnswers = typeof q.answers === 'string' ? JSON.parse(q.answers) : q.answers;

    await prisma.feladatok.create({
      data: {
        ...q,
        answers: normalizedAnswers,
      },
    });
  }

  console.log(`✅ Seeded ${questions.length} questions.`);
}
